name: staph-ngs
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.11
  - sra-tools
  - fastqc
  - multiqc
  - fastp
  - bwa
  - samtools
  - bcftools
  - vcftools
  - gatk4
  - wget
  - unzip
  - pigz
